# Generated by Django 4.1 on 2022-09-01 04:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('school', models.CharField(max_length=264)),
                ('classroom', models.CharField(choices=[('KC', 'Không Chuyên'), ('CT', 'Chuyên Toán'), ('CV', 'Chuyên Văn'), ('CL', 'Chuyên Lý'), ('CH', 'Chuyên Hóa'), ('CS', 'Chuyên Sinh'), ('CTin', 'Chuyên Tin'), ('CA', 'Chuyên Anh')], max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='BanChuyenTrach',
            fields=[
                ('ma_ban', models.AutoField(primary_key=True, serialize=False)),
                ('ten_ban', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mo_ta', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tieu_muc', models.IntegerField(null=True)),
                ('tieu_de', models.CharField(max_length=200)),
                ('tit', models.CharField(max_length=200, null=True)),
                ('tom_tat', models.TextField()),
                ('noi_dung', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ngay_gui_bai', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_xuat_ban', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_het_han', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
                ('nguon', models.CharField(max_length=200, null=True)),
                ('nguoi_gui', models.CharField(max_length=200, null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ma_muc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_muc', models.CharField(max_length=200)),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
                ('mo_ta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinh_thanh', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('lop_id', models.AutoField(primary_key=True, serialize=False)),
                ('lop', models.CharField(max_length=10, null=True)),
                ('ma_lop', models.CharField(max_length=10, null=True)),
                ('si_so', models.IntegerField(null=True)),
                ('giaovien', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(default='school/images/ptnkavatar.png', null=True, upload_to='school/images/')),
                ('isuser', models.BooleanField(default=False)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_dislikes', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.blog')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoanThe',
            fields=[
                ('ma_doan_the', models.AutoField(primary_key=True, serialize=False)),
                ('ten_doan_the', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mo_ta', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBD', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('toan', models.FloatField(blank=True, null=True)),
                ('van', models.FloatField(blank=True, null=True)),
                ('ly', models.FloatField(blank=True, null=True)),
                ('hoa', models.FloatField(blank=True, null=True)),
                ('su', models.FloatField(blank=True, null=True)),
                ('dia', models.FloatField(blank=True, null=True)),
                ('tin', models.FloatField(blank=True, null=True)),
                ('nn', models.FloatField(blank=True, null=True)),
                ('sinh', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('ma_khoi', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khoi', models.CharField(max_length=100)),
                ('khoi_tit', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('ma_thu_vien', models.AutoField(primary_key=True, serialize=False)),
                ('ten_thu_vien', models.CharField(max_length=100)),
                ('thuvien_tit', models.CharField(max_length=200, null=True)),
                ('ten_full', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NienKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nien_khoa', models.CharField(max_length=20)),
                ('tit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('ma_trang_thai', models.AutoField(primary_key=True, serialize=False)),
                ('trang_thai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ma_mon', models.AutoField(primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=100)),
                ('monhoc_tit', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='school/images/ptnkavatar.png', null=True, upload_to='school/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToBoMon',
            fields=[
                ('ma_to', models.AutoField(primary_key=True, serialize=False)),
                ('ten_to', models.CharField(max_length=200)),
                ('tit', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('mo_ta', ckeditor_uploader.fields.RichTextUploadingField()),
                ('gioithieu', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
                ('ma_muc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.category')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaHs', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('hinh', models.ImageField(default='school/images/default.png', null=True, upload_to='school/images')),
                ('ho_ten_cha', models.CharField(max_length=100, null=True)),
                ('ho_ten_me', models.CharField(max_length=100, null=True)),
                ('lop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(choices=[('Học kỳ 1', 'Học kỳ 1'), ('Học kỳ 2', 'Học kỳ 2')], max_length=10, null=True)),
                ('ky_thi', models.CharField(choices=[('Thường xuyên', 'Thường xuyên'), ('Giữa kỳ', 'Giữa kỳ'), ('Cuối kỳ', 'Cuối kỳ')], max_length=20, null=True)),
                ('lan_thi', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('diem_thi', models.FloatField(null=True)),
                ('ngay_thi', models.DateField(null=True)),
                ('MaHs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('mon_thi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('islike', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.blog')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_tai_lieu', models.CharField(max_length=200)),
                ('tit', models.CharField(max_length=200, null=True)),
                ('tom_tat', models.TextField()),
                ('pdf', models.CharField(max_length=200, null=True)),
                ('pdf_size', models.IntegerField(null=True)),
                ('file_goc', models.CharField(max_length=200, null=True)),
                ('file_goc_size', models.IntegerField(null=True)),
                ('ngay_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('ma_khoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('ma_mon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('ma_thu_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.library')),
                ('ma_trang_thai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.status')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='ma_khoi',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.PROTECT, to='school.grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='nienkhoa',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='school.nienkhoa'),
        ),
        migrations.AddField(
            model_name='blog',
            name='ma_muc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='ma_trang_thai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.status'),
        ),
    ]
